baseURL = "https://fbrv.github.io/"
title = "Yet another programming blog"
languageCode = "en-us"
theme = "PaperMod"
enableRobotsTXT = true
enableGitInfo = true

[params]
  author = "Fabio"
  description = "Thoughts on software, systems, and engineering"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true


[pagination]
  pagerSize = 10

[params.homeInfoParams]
  Title = "Hello, it's Fabio!"
  Content = "Undefined behavior, defined opinions."

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github"

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2
